valor = float(input("quantidade de antidoto"))
a = float(input("casca de colmeia"))
b = float(input("alho"))
c = float(input("óleo de troll"))
a = (float(input(valor*11.05/100)))
b = (float(input(valor*17.68/100)))
c = (float(input(valor*71.27/100)))
print(round(a,2))
print(round(b,2))
print(round(c,2))