peso= float(input("Peso do produto "))
dist= float(input("Distancia percorrida "))
valor_kg= float(peso * 25.00)
valor_km= float(dist * 0.10)
valor_icms= (((valor_kg + valor_km)/100) * 12)
preco = int(valor_icms + valor_kg + valor_km)
valor_imposto= int(preco * (valor_icms/100))
total= float(valor_kg + valor_km + valor_imposto)
print(round(total,2))