mg= float(input("Digite a massa do peixe grande: "))
vg= float(input("Digite a valocidade do peixe grande: "))
mp= float(input("Digite a massa do peixe pequeno: "))
vp= float(input("Digite a velocidade do peixe pequeno: "))
vf= (mg*vg-mp*vp)/(mg+mp)
print(vf)