bastardo = int("Digite o nome: ")

if (bastardo == "Snow)
   print("Norte")
if (bastardo == "Stone")
   print("Vale")
if (bastardo == "Rivers")
   print("Terras Fluviais")
if (bastardo == "Storm")
   print("Terras da Tempestade")
if (bastardo == "Sand")
   print("Dorne")
if (bastardo == "Pyke")
   print("Ilhas de Ferro")
if (bastardo == "Flowers")
   print("Campina")
if (bastardo == "Hill")
   print("Terras Ocidentais")
if (bastardo == "Waters")
   print("Terras da Coroa")
else:
	print("Entrada", bastardo, "valida")