mg = float(input("massa do peixe grande:"))
vg = float(input("velocidade do peixe grande:"))
mp = float(input("massa do peixe pequeno:"))
vp = float(input("velocidade do peixe pequeno:"))
vf = (((mg*vg)-(mp*vp))/(mg+mp))
print(vf)