peso=float(input("peso"))
distancia=float(input("distancia"))
codigo=float(input("codigo"))
cp=peso*25
dc=distancia*0.10
if(codigo==1):
	servico=(cp+dc)*(1+17/100)
	print(round(servico,2))
elif(codigo==2):
	servico=(cp+dc)*(1+17.5/100)
	print(round(servico,2))
elif(codigo==3):
	servico=(cp+dc)*(1+18/100)
	print(round(servico,2))
else:
	servico=(cp+dc)*(1+20/100)
	print(round(servico,2))