a=float(input("A"))
b=float(input("B"))
c=float(input("c"))
d=float(input("d"))
e=float(input("e"))
f=(a+b+c+d+e)/5
if(f>=6):
	print(round(f,2))
	print("Aprovacao")
else:
	print(round(f,2))
	print("Reprovacao")