c=input("Leia o nome da cidade: ")
if(c=="Pentos"):
	print("pentoshi")
elif(c=="Bravos"):
	print("bravosiano")
elif(c=="Lys"):
	print("liseno")
elif(c=="Qohor"):
	print("qohorik")
elif(c=="Norvos"):
	print("norvoshi")
elif(c=="Myr"):
	print("myrano")
elif(c=="Tyrosh"):
	print("tyroshi")
elif(c=="Volantis"):
	print("volantino")
elif(c=="Lorath"):
	print("lorathi")
else:
	print("Entrada",c,"invalida")